apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-producer
  name: location-producer
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30003
  selector:
    service: location-producer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-producer
  name: location-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-producer
  template:
    metadata:
      labels:
        service: location-producer
    spec:
      containers:
      - image: tinawu0603/location-producer:latest
        name: location-producer
        imagePullPolicy: Always
        env:
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: location-producer-kafka-configmap
              key: KAFKA_HOST
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: location-producer-kafka-configmap
              key: KAFKA_TOPIC
      restartPolicy: Always
