apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-consumer
  name: location-consumer
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30002
  selector:
    service: location-consumer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-consumer
  name: location-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-consumer
  template:
    metadata:
      labels:
        service: location-consumer
    spec:
      containers:
      - image: tinawu0603/location-consumer:latest
        name: location-consumer
        imagePullPolicy: Always
        env:
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: location-producer-kafka-configmap
              key: KAFKA_HOST
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: location-producer-kafka-configmap
              key: KAFKA_TOPIC
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: location-consumer-kafka-configmap
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: location-consumer-kafka-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: location-consumer-kafka-configmap
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: location-consumer-kafka-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: location-consumer-kafka-configmap
              key: DB_PORT
      restartPolicy: Always
